#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate etc/nvim/lua/pyinitial_data.lua from the upstream pinyin table.

The output file is checked into this repo, so end-users do **not** need to run
this script. Run it only when you want to refresh the embedded data
(for example, after a new release of mozillazg/pinyin-data).

Usage:
    python3 scripts/gen-pyinitial-data.py
    python3 scripts/gen-pyinitial-data.py --source /path/to/pinyin.txt
    python3 scripts/gen-pyinitial-data.py --range 0x4E00-0x9FFF
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

DEFAULT_SOURCE = (
    "https://raw.githubusercontent.com/mozillazg/pinyin-data/master/pinyin.txt"
)

TONE_MAP = str.maketrans({
    "ā": "a", "á": "a", "ǎ": "a", "à": "a",
    "ē": "e", "é": "e", "ě": "e", "è": "e",
    "ī": "i", "í": "i", "ǐ": "i", "ì": "i",
    "ō": "o", "ó": "o", "ǒ": "o", "ò": "o",
    "ū": "u", "ú": "u", "ǔ": "u", "ù": "u",
    "ǖ": "v", "ǘ": "v", "ǚ": "v", "ǜ": "v", "ü": "v",
    "ń": "n", "ň": "n", "ǹ": "n", "ḿ": "m",
})

LINE_RE = re.compile(r"U\+([0-9A-Fa-f]+):\s*([^#]+)#\s*(.+)")


def fetch(source: str) -> str:
    if source.startswith(("http://", "https://")):
        with urllib.request.urlopen(source, timeout=30) as r:
            return r.read().decode("utf-8")
    return Path(source).read_text(encoding="utf-8")


def parse_range(spec: str) -> tuple[int, int]:
    lo, hi = spec.split("-")
    return int(lo, 0), int(hi, 0)


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--source", default=DEFAULT_SOURCE,
                   help="URL or local path to pinyin.txt (default: upstream master)")
    p.add_argument("--range", default="0x4E00-0x9FFF",
                   help="codepoint range, hex (default: 0x4E00-0x9FFF, BMP CJK)")
    p.add_argument("--out", default=None,
                   help="output path (default: <repo>/etc/nvim/lua/pyinitial_data.lua)")
    args = p.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    out = Path(args.out) if args.out else repo_root / "etc/nvim/lua/pyinitial_data.lua"
    cp_lo, cp_hi = parse_range(args.range)

    print(f"[gen] source: {args.source}", file=sys.stderr)
    print(f"[gen] range:  U+{cp_lo:04X}–U+{cp_hi:04X}", file=sys.stderr)
    text = fetch(args.source)

    groups: dict[str, set[str]] = {chr(ord("a") + i): set() for i in range(26)}
    for line in text.splitlines():
        if not line or line.startswith("#") or ":" not in line:
            continue
        m = LINE_RE.match(line)
        if not m:
            continue
        cp = int(m.group(1), 16)
        if cp < cp_lo or cp > cp_hi:
            continue
        char = chr(cp)
        seen: set[str] = set()
        for reading in m.group(2).strip().split(","):
            reading = reading.strip().translate(TONE_MAP).lower()
            if reading and "a" <= reading[0] <= "z":
                seen.add(reading[0])
        for first in seen:
            groups[first].add(char)

    total = sum(len(v) for v in groups.values())
    distribution = {k: len(v) for k, v in groups.items()}

    lines = [
        "-- Auto-generated by scripts/gen-pyinitial-data.py",
        "-- Source: https://github.com/mozillazg/pinyin-data (MIT)",
        "-- Codepoint range: U+%04X to U+%04X" % (cp_lo, cp_hi),
        "-- 汉字按拼音首字母分组；多音字会出现在多个分组里。",
        "return {",
    ]
    for letter in "abcdefghijklmnopqrstuvwxyz":
        chars = "".join(sorted(groups[letter]))
        lines.append(f'  {letter} = [[{chars}]],')
    lines.append("}")
    lines.append("")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")

    print(f"[gen] wrote {out} ({out.stat().st_size} bytes, {total} chars)", file=sys.stderr)
    print(f"[gen] distribution per initial: {distribution}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
